### ISSUE TITLE
FundamentosIS_Informe de entrevista

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/entrevista-equipo-systems#1]
[FundamentosIS_Informe de entrevista.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-equipo-systems/files/7147525/FundamentosIS_Informe.de.entrevista.pdf)

**Comment by Yabin-2021** [comment]
Muy buen Trabajo...
Puntaje **20 %**

**Comment by KarlaV0** [comment]
AUDIO DE LA ENTREVISTA
[https://drive.google.com/file/d/1jbumprvCJ9Yrt7nqnMKPj6twDkFlCNnx/view?usp=sharing](url)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
